target = 'EnVar'

files = Split("""
	envar.c
""")

libs = Split("""
	kernel32
	user32
	advapi32
""")

examples = Split("""
	example.nsi
""")

docs = Split("""
	license.txt
	readme.txt
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, examples, docs)
